### ISSUE TITLE
ArtifactoryGenericDownload not working in version 1.9.1

### ISSUE THREAD

**Issue by guidorubin** [jfrog/artifactory-azure-devops-extension#153]
Please Help..
Log:

2020-04-23T14:16:48.2820183Z ##[debug]Evaluating condition for step: 'ArtifactoryGenericDownload'
2020-04-23T14:16:48.2822182Z ##[debug]Evaluating: SucceededNode()
2020-04-23T14:16:48.2822958Z ##[debug]Evaluating SucceededNode:
2020-04-23T14:16:48.2824097Z ##[debug]=> True
2020-04-23T14:16:48.2824817Z ##[debug]Result: True
2020-04-23T14:16:48.2825565Z ##[section]Starting: ArtifactoryGenericDownload
2020-04-23T14:16:48.2940275Z ==============================================================================
2020-04-23T14:16:48.2940750Z Task         : Artifactory Generic Download
2020-04-23T14:16:48.2941440Z Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
2020-04-23T14:16:48.2942071Z Version      : 2.9.1
2020-04-23T14:16:48.2942383Z Author       : JFrog
2020-04-23T14:16:48.2942707Z Help         : 
2020-04-23T14:16:48.2943081Z ==============================================================================
2020-04-23T14:16:48.4287478Z module.js:478
2020-04-23T14:16:48.4290551Z     throw err;
2020-04-23T14:16:48.4291096Z     ^
2020-04-23T14:16:48.4291531Z 
2020-04-23T14:16:48.4292046Z Error: Cannot find module 'azure-pipelines-task-lib/task'
2020-04-23T14:16:48.4292678Z     at Function.Module._resolveFilename (module.js:476:15)
2020-04-23T14:16:48.4293335Z     at Function.Module._load (module.js:424:25)
2020-04-23T14:16:48.4293894Z     at Module.require (module.js:504:17)
2020-04-23T14:16:48.4294438Z     at require (internal/module.js:20:19)
2020-04-23T14:16:48.4295503Z     at Object.<anonymous> (d:\a\_tasks\ArtifactoryGenericDownload_07fc5c20-6772-11e5-abde-6901d3c00755\2.9.1\downloadArtifacts.js:1:74)
2020-04-23T14:16:48.4297572Z     at Module._compile (module.js:577:32)
2020-04-23T14:16:48.4299049Z     at Object.Module._extensions..js (module.js:586:10)
2020-04-23T14:16:48.4299774Z     at Module.load (module.js:494:32)
2020-04-23T14:16:48.4300335Z     at tryModuleLoad (module.js:453:12)
2020-04-23T14:16:48.4300941Z     at Function.Module._load (module.js:445:3)
2020-04-23T14:16:48.4506254Z ##[error]Exit code 1 returned from process: file name 'C:\agents\2.166.3\externals\node\bin\node.exe', arguments '"d:\a\_tasks\ArtifactoryGenericDownload_07fc5c20-6772-11e5-abde-6901d3c00755\2.9.1\downloadArtifacts.js"'.
2020-04-23T14:16:48.4522870Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\agents\2.166.3\externals\node\bin\node.exe', arguments '"d:\a\_tasks\ArtifactoryGenericDownload_07fc5c20-6772-11e5-abde-6901d3c00755\2.9.1\downloadArtifacts.js"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2020-04-23T14:16:48.4529021Z ##[section]Finishing: ArtifactoryGenericDownload

**Comment by guidorubin** [comment]
Can anyone help on this?

Thanks in advance.

**Comment by yahavi** [comment]
Thanks for reporting this issue, @guidorubin.
This issue is fixed in the last version 1.9.2.
For more information see: https://github.com/jfrog/artifactory-azure-devops-extension/issues/149#issuecomment-613489020.

We'll appreciate your feedback for that.

**Comment by guidorubin** [comment]
Hi @yahavi thanks for answering me. 
Yep, I thought that was fixed in 1.9.2.

My question is how can update the plugin in Azure? Do you know? 

I have this:

![image](https://user-images.githubusercontent.com/10190583/81003922-fa24c480-8e21-11ea-967c-8c20cd69d481.png)

But I don't know how to update it. Do you know?

**Comment by yahavi** [comment]
It should have been upgraded automatically by Azure DevOps.
However, some users said they had to reinstall the extension to upgrade.

**Comment by guidorubin** [comment]
Thanks! I will try it and let you know! 👍

**Comment by guidorubin** [comment]
![image](https://user-images.githubusercontent.com/10190583/81097442-4d5c4d00-8ede-11ea-8fbe-dfec88d9e640.png)

Got it!!! Closing the issue! Thanks a ton @yahavi  💪
